create table bags (bag varchar(max))
insert into bags
		  select 'muted lime bags contain 1 wavy lime bag, 1 vibrant green bag, 3 light yellow bags.'
union all select 'light red bags contain 2 clear indigo bags, 3 light lime bags.'
union all select 'wavy beige bags contain 4 faded chartreuse bags.'
union all select 'muted blue bags contain 3 mirrored tan bags.'
union all select 'vibrant cyan bags contain 4 drab beige bags, 4 vibrant maroon bags, 2 dull coral bags.'
union all select 'posh indigo bags contain 1 dim cyan bag, 4 striped violet bags, 2 posh olive bags.'
union all select 'dark black bags contain 5 dotted purple bags, 3 dotted orange bags, 5 shiny gold bags, 3 wavy brown bags.'
union all select 'dull teal bags contain 1 posh aqua bag.'
union all select 'dim aqua bags contain 3 muted indigo bags, 5 vibrant green bags, 3 dotted teal bags.'
union all select 'clear bronze bags contain 1 plaid gold bag, 4 pale tan bags, 1 light teal bag, 5 dim lavender bags.'
union all select 'shiny fuchsia bags contain 5 striped orange bags, 2 faded plum bags.'
union all select 'dim bronze bags contain 2 plaid tan bags, 4 muted green bags.'
union all select 'muted white bags contain 1 wavy black bag, 2 striped olive bags.'
union all select 'wavy maroon bags contain 3 striped magenta bags, 3 bright teal bags, 2 dark crimson bags.'
union all select 'muted beige bags contain 4 dull plum bags, 2 plaid fuchsia bags, 3 clear coral bags, 1 clear red bag.'
union all select 'drab chartreuse bags contain 2 dull gray bags, 2 striped olive bags, 2 dark aqua bags.'
union all select 'plaid turquoise bags contain 1 muted teal bag.'
union all select 'muted maroon bags contain 1 faded chartreuse bag, 1 wavy gray bag, 5 faded black bags, 2 posh tan bags.'
union all select 'muted bronze bags contain 1 muted white bag.'
union all select 'muted teal bags contain 1 striped beige bag.'
union all select 'faded indigo bags contain 5 mirrored green bags.'
union all select 'drab tan bags contain 4 dim lavender bags.'
union all select 'bright turquoise bags contain 2 pale olive bags, 4 posh salmon bags.'
union all select 'dull aqua bags contain 2 dark orange bags, 2 pale aqua bags, 1 faded plum bag.'
union all select 'striped coral bags contain 3 wavy purple bags, 2 dull gray bags.'
union all select 'muted chartreuse bags contain 3 dark purple bags, 2 posh gray bags.'
union all select 'wavy plum bags contain 2 dark lavender bags, 2 shiny turquoise bags, 5 wavy beige bags, 5 pale maroon bags.'
union all select 'vibrant maroon bags contain 1 light lime bag, 1 light silver bag, 5 bright orange bags, 2 shiny red bags.'
union all select 'mirrored purple bags contain 3 bright olive bags, 3 bright yellow bags, 5 muted white bags.'
union all select 'muted magenta bags contain 5 plaid indigo bags.'
union all select 'drab lavender bags contain 1 faded beige bag, 2 muted gray bags, 2 dotted purple bags.'
union all select 'plaid cyan bags contain 4 plaid violet bags, 5 posh chartreuse bags.'
union all select 'plaid aqua bags contain 2 wavy gray bags, 4 light fuchsia bags, 4 muted white bags.'
union all select 'wavy bronze bags contain 4 light bronze bags, 3 light tomato bags, 5 shiny tomato bags.'
union all select 'wavy aqua bags contain 4 plaid crimson bags, 3 muted brown bags, 1 pale tan bag.'
union all select 'bright violet bags contain 1 wavy tan bag, 4 light coral bags, 1 vibrant plum bag.'
union all select 'pale yellow bags contain 4 light lime bags, 2 striped violet bags, 1 plaid orange bag, 3 dull lavender bags.'
union all select 'plaid olive bags contain 1 mirrored magenta bag, 3 posh silver bags, 1 plaid brown bag.'
union all select 'wavy brown bags contain 4 shiny black bags, 3 wavy plum bags.'
union all select 'clear turquoise bags contain 5 dotted beige bags.'
union all select 'striped fuchsia bags contain 2 dim tan bags.'
union all select 'pale coral bags contain 1 plaid coral bag, 5 striped salmon bags.'
union all select 'plaid magenta bags contain 4 plaid aqua bags, 2 dim cyan bags, 2 vibrant teal bags.'
union all select 'dim beige bags contain 5 shiny gold bags, 2 wavy brown bags.'
union all select 'clear violet bags contain 2 striped silver bags.'
union all select 'light lime bags contain 5 muted teal bags.'
union all select 'pale plum bags contain 2 vibrant lavender bags.'
union all select 'drab black bags contain 3 light white bags, 2 dim tomato bags, 3 dull yellow bags, 2 plaid coral bags.'
union all select 'vibrant lime bags contain 5 wavy gray bags, 5 striped green bags, 5 striped black bags.'
union all select 'faded fuchsia bags contain 3 shiny aqua bags.'
union all select 'vibrant olive bags contain 2 striped olive bags.'
union all select 'dark indigo bags contain 5 pale maroon bags, 2 striped turquoise bags.'
union all select 'dark cyan bags contain 3 light gold bags, 1 plaid lime bag, 1 dim indigo bag.'
union all select 'clear tomato bags contain 3 plaid tan bags, 2 vibrant blue bags.'
union all select 'muted yellow bags contain 2 dotted coral bags.'
union all select 'muted brown bags contain 1 vibrant green bag, 3 bright green bags, 2 plaid fuchsia bags.'
union all select 'dark bronze bags contain 2 clear orange bags.'
union all select 'dotted turquoise bags contain 4 faded black bags, 3 plaid crimson bags, 3 faded beige bags.'
union all select 'shiny violet bags contain 4 muted blue bags, 2 light purple bags, 5 striped magenta bags, 3 dark black bags.'
union all select 'dotted orange bags contain 3 striped tan bags, 2 posh brown bags, 2 muted white bags, 5 dark crimson bags.'
union all select 'shiny gold bags contain 1 clear coral bag, 1 muted green bag, 5 muted teal bags, 4 dull olive bags.'
union all select 'clear brown bags contain 1 shiny tomato bag.'
union all select 'shiny beige bags contain 4 dotted chartreuse bags.'
union all select 'dotted tomato bags contain 5 dull aqua bags.'
union all select 'dull black bags contain 2 muted purple bags.'
union all select 'wavy turquoise bags contain 5 striped beige bags, 2 dark silver bags, 2 light beige bags, 5 dull olive bags.'
union all select 'bright coral bags contain 4 pale crimson bags, 4 striped coral bags, 3 drab cyan bags, 4 vibrant aqua bags.'
union all select 'mirrored salmon bags contain 1 wavy orange bag, 1 dark lime bag.'
union all select 'clear chartreuse bags contain 4 muted indigo bags, 5 dotted gray bags.'
union all select 'dim chartreuse bags contain 1 clear lime bag, 3 muted gray bags, 5 vibrant blue bags, 4 mirrored gold bags.'
union all select 'vibrant purple bags contain 4 dull brown bags, 5 clear aqua bags, 2 bright bronze bags, 5 shiny lavender bags.'
union all select 'pale turquoise bags contain 3 light black bags, 1 dim tan bag.'
union all select 'mirrored black bags contain 1 wavy beige bag.'
union all select 'striped white bags contain 4 dim chartreuse bags, 2 pale lime bags, 1 faded orange bag.'
union all select 'faded bronze bags contain 5 drab cyan bags.'
union all select 'dull coral bags contain 5 dull crimson bags, 3 plaid silver bags.'
union all select 'posh gray bags contain 4 muted indigo bags, 4 bright cyan bags, 1 faded black bag.'
union all select 'vibrant bronze bags contain 4 posh crimson bags, 4 mirrored silver bags, 1 dark turquoise bag, 1 pale maroon bag.'
union all select 'posh lavender bags contain 1 vibrant gold bag, 3 faded maroon bags, 4 striped magenta bags, 3 wavy gold bags.'
union all select 'clear olive bags contain 1 posh tomato bag, 2 clear lime bags, 1 plaid yellow bag.'
union all select 'bright orange bags contain 4 light aqua bags, 3 vibrant teal bags, 5 dull crimson bags, 3 dark fuchsia bags.'
union all select 'dotted lavender bags contain 1 posh beige bag, 5 faded cyan bags, 1 dark olive bag.'
union all select 'posh beige bags contain 3 dotted blue bags, 4 faded indigo bags.'
union all select 'dull indigo bags contain 4 clear green bags, 5 muted bronze bags.'
union all select 'mirrored brown bags contain 5 muted beige bags, 3 dull chartreuse bags, 4 shiny black bags, 1 dim green bag.'
union all select 'bright silver bags contain 3 clear white bags, 5 light tomato bags, 5 plaid blue bags.'
union all select 'dotted teal bags contain no other bags.'
union all select 'light brown bags contain 1 faded indigo bag, 3 dotted coral bags.'
union all select 'light indigo bags contain 1 plaid red bag, 5 vibrant magenta bags, 4 pale lavender bags.'
union all select 'drab beige bags contain 1 dotted gold bag, 3 clear black bags.'
union all select 'striped orange bags contain 3 shiny red bags, 4 striped olive bags, 1 posh maroon bag.'
union all select 'bright lavender bags contain no other bags.'
union all select 'clear yellow bags contain 5 mirrored green bags, 4 striped red bags, 3 plaid magenta bags, 1 bright lavender bag.'
union all select 'pale bronze bags contain 4 bright beige bags, 4 muted beige bags, 3 pale salmon bags.'
union all select 'light salmon bags contain 3 shiny brown bags.'
union all select 'shiny plum bags contain 5 dotted turquoise bags.'
union all select 'dotted red bags contain 2 muted bronze bags, 2 dull yellow bags, 4 drab turquoise bags.'
union all select 'faded white bags contain 1 striped beige bag.'
union all select 'bright olive bags contain 1 posh brown bag, 2 mirrored red bags.'
union all select 'light gray bags contain 5 wavy lavender bags, 5 vibrant yellow bags.'
union all select 'mirrored indigo bags contain 1 wavy turquoise bag, 5 muted green bags.'
union all select 'light black bags contain 3 light fuchsia bags, 3 plaid fuchsia bags, 5 mirrored green bags.'
union all select 'striped maroon bags contain 4 dull fuchsia bags, 1 striped olive bag, 1 mirrored gold bag, 4 light violet bags.'
union all select 'mirrored silver bags contain 2 posh tan bags, 2 mirrored magenta bags, 1 dark orange bag.'
union all select 'pale aqua bags contain 5 dim tan bags, 4 muted black bags.'
union all select 'pale gray bags contain 2 clear plum bags.'
union all select 'faded turquoise bags contain 5 faded black bags, 3 shiny black bags.'
union all select 'dotted indigo bags contain 4 plaid green bags, 4 dull brown bags, 1 plaid magenta bag, 2 plaid tomato bags.'
union all select 'vibrant silver bags contain 3 drab chartreuse bags.'
union all select 'dotted crimson bags contain 1 drab coral bag, 2 shiny red bags, 2 dotted plum bags, 4 mirrored yellow bags.'
union all select 'clear orange bags contain 4 wavy black bags, 2 drab coral bags, 1 bright lavender bag, 2 dull olive bags.'
union all select 'mirrored violet bags contain 4 striped tan bags.'
union all select 'bright tan bags contain 1 mirrored gold bag, 1 dotted turquoise bag, 4 wavy orange bags.'
union all select 'dull bronze bags contain 3 shiny chartreuse bags, 2 dark beige bags.'
union all select 'vibrant white bags contain 4 plaid tan bags, 1 wavy black bag.'
union all select 'wavy green bags contain 2 muted fuchsia bags, 3 plaid gold bags, 3 striped green bags, 5 dim cyan bags.'
union all select 'striped brown bags contain 3 vibrant olive bags, 2 plaid orange bags.'
union all select 'wavy lavender bags contain 2 muted orange bags, 4 clear maroon bags, 5 bright tomato bags.'
union all select 'bright purple bags contain 4 dim crimson bags.'
union all select 'pale fuchsia bags contain 5 bright lime bags.'
union all select 'posh aqua bags contain 5 clear lime bags, 1 shiny turquoise bag, 5 bright cyan bags, 2 dim chartreuse bags.'
union all select 'dark olive bags contain 5 shiny tan bags, 5 plaid red bags, 5 pale lavender bags.'
union all select 'striped silver bags contain 3 bright plum bags.'
union all select 'striped tomato bags contain 1 pale maroon bag, 1 clear yellow bag.'
union all select 'faded beige bags contain 1 light fuchsia bag.'
union all select 'plaid green bags contain 5 light fuchsia bags.'
union all select 'drab silver bags contain 4 vibrant white bags.'
union all select 'striped indigo bags contain 4 shiny green bags, 2 dark beige bags.'
union all select 'mirrored teal bags contain 3 muted green bags, 5 muted gray bags.'
union all select 'posh gold bags contain 3 wavy beige bags, 5 muted lavender bags, 1 striped tan bag.'
union all select 'wavy red bags contain 2 dim beige bags.'
union all select 'dull plum bags contain 2 drab coral bags, 3 wavy black bags.'
union all select 'bright crimson bags contain 2 posh silver bags, 3 vibrant plum bags, 5 posh brown bags.'
union all select 'clear gray bags contain 1 dotted white bag, 2 posh aqua bags.'
union all select 'striped aqua bags contain 1 muted black bag, 5 dim bronze bags, 3 striped olive bags, 1 plaid turquoise bag.'
union all select 'dark tomato bags contain 2 dull olive bags, 1 plaid aqua bag, 4 faded fuchsia bags, 4 muted gray bags.'
union all select 'vibrant yellow bags contain 5 dim blue bags, 5 dim crimson bags, 1 dotted aqua bag.'
union all select 'shiny salmon bags contain 4 bright lavender bags, 2 faded black bags, 5 mirrored salmon bags.'
union all select 'wavy salmon bags contain 1 plaid aqua bag, 2 mirrored fuchsia bags, 2 muted green bags.'
union all select 'faded cyan bags contain 5 plaid fuchsia bags, 4 dull gray bags.'
union all select 'clear coral bags contain 1 striped olive bag.'
union all select 'bright white bags contain 1 muted gray bag.'
union all select 'dim salmon bags contain 1 faded red bag, 2 striped plum bags.'
union all select 'dotted silver bags contain 5 faded lime bags, 2 drab black bags, 2 mirrored teal bags, 2 drab tomato bags.'
union all select 'bright teal bags contain 5 dotted gray bags.'
union all select 'faded red bags contain 3 light purple bags, 5 plaid yellow bags.'
union all select 'muted salmon bags contain 3 clear yellow bags.'
union all select 'shiny turquoise bags contain 2 dark lavender bags, 1 dark crimson bag.'
union all select 'muted indigo bags contain 4 dark lavender bags, 1 posh olive bag.'
union all select 'wavy gray bags contain no other bags.'
union all select 'muted olive bags contain 3 bright tomato bags, 4 plaid coral bags, 4 dull orange bags, 2 wavy brown bags.'
union all select 'clear black bags contain 1 dim chartreuse bag, 5 dark aqua bags, 5 dotted teal bags.'
union all select 'faded yellow bags contain 1 drab salmon bag, 1 bright lavender bag.'
union all select 'shiny yellow bags contain 3 dark olive bags, 1 bright tomato bag, 3 dim fuchsia bags.'
union all select 'clear blue bags contain 2 light coral bags, 2 faded beige bags, 4 muted indigo bags, 1 faded blue bag.'
union all select 'dim lime bags contain 5 striped tan bags, 4 light black bags, 1 dark orange bag.'
union all select 'wavy coral bags contain 2 mirrored black bags, 4 vibrant coral bags, 1 pale chartreuse bag.'
union all select 'wavy fuchsia bags contain 4 shiny silver bags.'
union all select 'dim silver bags contain 3 clear blue bags.'
union all select 'plaid chartreuse bags contain 2 clear plum bags.'
union all select 'pale blue bags contain 4 pale magenta bags.'
union all select 'drab red bags contain 3 plaid cyan bags, 3 light yellow bags.'
union all select 'dull gold bags contain 5 clear lime bags, 5 plaid coral bags.'
union all select 'shiny indigo bags contain 3 dim bronze bags, 5 dotted teal bags.'
union all select 'light purple bags contain 5 light lime bags, 1 shiny plum bag.'
union all select 'mirrored cyan bags contain 5 clear lime bags.'
union all select 'posh chartreuse bags contain 2 striped olive bags.'
union all select 'dark gray bags contain 5 vibrant maroon bags, 2 dark olive bags.'
union all select 'clear lavender bags contain 3 striped magenta bags, 3 pale lavender bags, 2 dotted chartreuse bags, 4 dim tan bags.'
union all select 'faded lavender bags contain 5 striped lavender bags, 2 mirrored yellow bags, 4 bright purple bags.'
union all select 'striped tan bags contain 3 drab coral bags, 3 vibrant indigo bags.'
union all select 'dim violet bags contain 4 wavy black bags, 3 faded indigo bags, 2 wavy gray bags, 5 striped red bags.'
union all select 'dotted magenta bags contain 5 shiny indigo bags, 3 mirrored red bags.'
union all select 'shiny blue bags contain 4 light tan bags, 4 striped black bags, 1 vibrant teal bag, 4 shiny gray bags.'
union all select 'bright gray bags contain 5 clear tomato bags, 5 dark lavender bags.'
union all select 'dark turquoise bags contain 5 dull lime bags, 3 dim green bags, 3 pale tan bags.'
union all select 'clear beige bags contain 3 drab aqua bags.'
union all select 'pale olive bags contain 4 dark green bags, 1 posh crimson bag.'
union all select 'posh fuchsia bags contain 3 dim green bags, 3 posh maroon bags, 1 posh olive bag, 4 muted fuchsia bags.'
union all select 'posh bronze bags contain 5 striped olive bags, 2 dark lavender bags, 4 posh tan bags.'
union all select 'shiny bronze bags contain 4 dotted plum bags, 4 clear indigo bags.'
union all select 'wavy magenta bags contain 2 dim chartreuse bags, 2 mirrored gold bags, 2 wavy gold bags.'
union all select 'dull yellow bags contain 4 plaid tan bags.'
union all select 'mirrored tomato bags contain 3 light violet bags.'
union all select 'light turquoise bags contain 3 bright yellow bags, 1 drab blue bag.'
union all select 'plaid maroon bags contain 2 plaid magenta bags.'
union all select 'pale silver bags contain 2 wavy bronze bags, 3 striped tan bags.'
union all select 'striped blue bags contain 1 dark crimson bag, 4 dull purple bags, 4 bright tomato bags.'
union all select 'faded blue bags contain 2 posh olive bags, 1 clear silver bag, 5 faded turquoise bags.'
union all select 'dark blue bags contain 5 vibrant gray bags, 3 pale lavender bags.'
union all select 'light fuchsia bags contain 1 dotted teal bag, 2 shiny red bags, 4 bright cyan bags.'
union all select 'dull chartreuse bags contain 5 dull olive bags, 2 dull gray bags.'
union all select 'pale orange bags contain 2 striped lavender bags, 3 dotted red bags.'
union all select 'dark silver bags contain 1 muted white bag, 3 striped aqua bags, 3 dim aqua bags, 2 striped tan bags.'
union all select 'dark lavender bags contain 3 wavy gray bags, 4 dim chartreuse bags, 1 bright lavender bag, 3 muted gray bags.'
union all select 'light beige bags contain 4 dim aqua bags, 5 mirrored teal bags.'
union all select 'plaid violet bags contain 2 clear plum bags, 2 striped olive bags.'
union all select 'plaid orange bags contain 1 dim maroon bag, 1 dim bronze bag, 5 muted white bags.'
union all select 'faded crimson bags contain 3 faded cyan bags.'
union all select 'muted plum bags contain 5 bright teal bags.'
union all select 'striped crimson bags contain 3 shiny violet bags, 4 striped beige bags, 5 wavy violet bags.'
union all select 'shiny lime bags contain 5 dim green bags, 5 mirrored black bags.'
union all select 'muted lavender bags contain 4 mirrored magenta bags, 4 wavy yellow bags, 5 pale gold bags, 2 light cyan bags.'
union all select 'drab aqua bags contain 3 plaid blue bags, 3 pale bronze bags, 3 bright magenta bags.'
union all select 'dark yellow bags contain 4 bright salmon bags, 2 dim yellow bags.'
union all select 'posh teal bags contain 1 clear crimson bag.'
union all select 'clear fuchsia bags contain 1 vibrant blue bag, 2 shiny lavender bags, 3 faded teal bags, 4 plaid green bags.'
union all select 'bright yellow bags contain 4 mirrored coral bags, 2 dull purple bags, 3 dim indigo bags, 5 dark white bags.'
union all select 'pale purple bags contain 2 vibrant olive bags, 1 dark fuchsia bag, 3 faded turquoise bags.'
union all select 'dotted coral bags contain 4 dark crimson bags.'
union all select 'plaid beige bags contain 2 striped maroon bags, 4 mirrored fuchsia bags, 5 shiny turquoise bags, 3 clear plum bags.'
union all select 'plaid white bags contain 5 posh chartreuse bags, 4 dark crimson bags.'
union all select 'shiny black bags contain 4 dim brown bags, 5 plaid tan bags, 5 plaid orange bags.'
union all select 'dim teal bags contain 1 wavy aqua bag.'
union all select 'dim yellow bags contain 2 muted bronze bags, 1 bright indigo bag.'
union all select 'dim tan bags contain 1 plaid turquoise bag, 4 vibrant plum bags, 2 plaid aqua bags.'
union all select 'bright salmon bags contain 3 dim blue bags, 5 wavy gray bags, 2 bright maroon bags.'
union all select 'posh plum bags contain 2 dark cyan bags, 1 bright orange bag, 1 dotted crimson bag, 4 dark tan bags.'
union all select 'muted crimson bags contain 1 striped beige bag, 4 muted salmon bags, 1 faded tan bag, 3 dull fuchsia bags.'
union all select 'mirrored lavender bags contain 3 light black bags, 4 posh salmon bags, 2 shiny black bags.'
union all select 'dim olive bags contain 2 bright green bags, 3 bright magenta bags, 4 striped silver bags, 1 vibrant indigo bag.'
union all select 'faded coral bags contain 5 posh blue bags, 5 dotted maroon bags, 3 dark maroon bags.'
union all select 'striped cyan bags contain 2 vibrant purple bags, 2 shiny silver bags, 5 clear tan bags, 4 muted orange bags.'
union all select 'striped beige bags contain 2 bright lavender bags, 3 mirrored gold bags, 4 dull fuchsia bags, 4 dull gray bags.'
union all select 'mirrored magenta bags contain 5 posh crimson bags, 1 pale magenta bag, 3 striped maroon bags, 4 shiny turquoise bags.'
union all select 'vibrant chartreuse bags contain 2 light beige bags, 4 dark white bags.'
union all select 'mirrored fuchsia bags contain 4 plaid red bags.'
union all select 'vibrant turquoise bags contain 4 light teal bags, 5 plaid salmon bags, 2 muted tan bags, 5 posh tomato bags.'
union all select 'faded gray bags contain 2 dull white bags, 1 plaid orange bag.'
union all select 'bright bronze bags contain 4 muted teal bags, 3 dark crimson bags, 4 posh tan bags.'
union all select 'plaid lime bags contain 3 striped turquoise bags.'
union all select 'pale teal bags contain 5 shiny silver bags, 4 posh plum bags, 3 plaid salmon bags.'
union all select 'dark chartreuse bags contain 5 bright plum bags, 2 faded beige bags, 1 vibrant chartreuse bag.'
union all select 'dull crimson bags contain 5 light beige bags, 4 muted purple bags, 4 dotted chartreuse bags, 4 faded turquoise bags.'
union all select 'dotted salmon bags contain 3 faded indigo bags, 1 dotted gold bag, 3 light lime bags.'
union all select 'bright black bags contain 2 dim yellow bags, 3 vibrant coral bags, 5 light coral bags.'
union all select 'plaid blue bags contain 4 mirrored tomato bags, 5 faded fuchsia bags, 5 dull chartreuse bags.'
union all select 'shiny white bags contain 4 dim maroon bags, 1 dim gray bag, 2 light white bags, 3 dull tan bags.'
union all select 'muted cyan bags contain 2 pale cyan bags.'
union all select 'dim red bags contain 1 faded indigo bag.'
union all select 'mirrored tan bags contain 4 striped magenta bags, 1 clear chartreuse bag.'
union all select 'bright blue bags contain 2 wavy turquoise bags.'
union all select 'pale tan bags contain 2 faded black bags.'
union all select 'dark green bags contain 1 pale salmon bag.'
union all select 'pale beige bags contain 2 bright chartreuse bags, 4 faded bronze bags.'
union all select 'dotted gold bags contain 2 wavy black bags, 1 dotted coral bag, 4 dim maroon bags, 5 dark green bags.'
union all select 'dark magenta bags contain 2 wavy yellow bags, 1 dark cyan bag.'
union all select 'bright chartreuse bags contain 4 dotted blue bags, 3 shiny aqua bags, 1 muted crimson bag, 4 dull blue bags.'
union all select 'dotted black bags contain 4 posh gray bags, 4 striped white bags, 2 faded green bags, 2 shiny indigo bags.'
union all select 'posh red bags contain 4 clear chartreuse bags, 4 plaid maroon bags, 2 striped orange bags.'
union all select 'dark aqua bags contain 1 vibrant indigo bag, 1 dark crimson bag.'
union all select 'drab indigo bags contain 2 vibrant salmon bags, 2 shiny purple bags.'
union all select 'dull lavender bags contain 4 vibrant plum bags, 3 vibrant indigo bags, 3 clear lime bags.'
union all select 'dull magenta bags contain 4 mirrored white bags, 3 clear olive bags, 5 striped plum bags.'
union all select 'dotted chartreuse bags contain 3 striped beige bags, 4 wavy gray bags.'
union all select 'dotted yellow bags contain 3 plaid white bags, 2 posh gray bags.'
union all select 'vibrant red bags contain 5 clear cyan bags.'
union all select 'dim orange bags contain 4 drab chartreuse bags, 3 muted teal bags.'
union all select 'shiny brown bags contain 3 dim maroon bags.'
union all select 'posh green bags contain 5 muted brown bags, 1 dark crimson bag.'
union all select 'pale lime bags contain 3 muted gray bags, 5 dotted coral bags, 5 faded black bags, 2 vibrant white bags.'
union all select 'dim maroon bags contain 2 wavy gray bags, 4 plaid fuchsia bags.'
union all select 'bright beige bags contain 3 striped maroon bags, 2 striped magenta bags, 3 light teal bags, 2 shiny red bags.'
union all select 'drab magenta bags contain 2 posh olive bags.'
union all select 'wavy white bags contain 3 plaid tomato bags, 1 dotted gray bag, 2 mirrored bronze bags.'
union all select 'posh coral bags contain 2 wavy coral bags, 5 mirrored tan bags, 1 pale gray bag.'
union all select 'plaid gray bags contain 3 faded green bags, 5 faded olive bags, 4 drab white bags, 3 wavy green bags.'
union all select 'bright plum bags contain 1 dark aqua bag, 4 shiny red bags, 2 vibrant white bags.'
union all select 'plaid tomato bags contain 2 light lime bags, 3 vibrant white bags.'
union all select 'pale brown bags contain 1 faded brown bag.'
union all select 'muted gray bags contain 3 posh olive bags, 4 plaid fuchsia bags, 3 vibrant blue bags.'
union all select 'dotted green bags contain 1 dim lavender bag, 4 striped chartreuse bags, 3 bright maroon bags.'
union all select 'striped yellow bags contain 4 pale white bags, 2 bright blue bags, 5 faded orange bags, 2 dull violet bags.'
union all select 'mirrored chartreuse bags contain 2 shiny indigo bags, 2 mirrored teal bags.'
union all select 'posh olive bags contain 4 muted purple bags, 1 dull gray bag, 1 striped beige bag.'
union all select 'posh salmon bags contain 5 dim yellow bags, 2 dark purple bags.'
union all select 'drab gold bags contain 3 posh white bags, 3 dotted salmon bags, 2 vibrant coral bags.'
union all select 'faded silver bags contain 2 wavy magenta bags.'
union all select 'dim blue bags contain 2 clear lime bags.'
union all select 'faded black bags contain 4 dark crimson bags, 2 dark aqua bags, 1 mirrored teal bag, 4 dull brown bags.'
union all select 'striped lavender bags contain 4 plaid red bags, 1 light black bag, 2 bright cyan bags, 2 muted tan bags.'
union all select 'mirrored olive bags contain 2 plaid beige bags, 1 wavy aqua bag, 3 faded tomato bags.'
union all select 'wavy lime bags contain 1 mirrored brown bag, 5 posh cyan bags.'
union all select 'dim crimson bags contain 2 drab chartreuse bags, 1 posh lavender bag.'
union all select 'dim black bags contain 2 dull black bags, 3 vibrant maroon bags, 2 light fuchsia bags.'
union all select 'drab cyan bags contain 3 striped turquoise bags.'
union all select 'dim brown bags contain 5 dim orange bags, 5 dull brown bags, 1 dotted teal bag, 3 dark white bags.'
union all select 'vibrant magenta bags contain 1 light crimson bag, 4 light maroon bags.'
union all select 'dotted fuchsia bags contain 1 dark green bag, 3 wavy gold bags, 3 bright indigo bags.'
union all select 'light crimson bags contain 2 pale chartreuse bags.'
union all select 'posh crimson bags contain 5 plaid tan bags, 1 dark lavender bag, 4 light lime bags.'
union all select 'dark fuchsia bags contain 5 mirrored coral bags, 5 vibrant olive bags, 4 light black bags.'
union all select 'faded chartreuse bags contain 3 drab coral bags, 1 dim chartreuse bag, 4 dotted chartreuse bags, 1 muted teal bag.'
union all select 'dotted lime bags contain 1 shiny turquoise bag, 3 vibrant plum bags, 5 vibrant teal bags.'
union all select 'light teal bags contain 3 bright plum bags.'
union all select 'shiny chartreuse bags contain 5 vibrant green bags, 1 dim blue bag.'
union all select 'vibrant tomato bags contain 1 clear tan bag, 3 faded magenta bags, 2 clear cyan bags, 2 dark silver bags.'
union all select 'posh cyan bags contain 1 vibrant white bag, 2 dull white bags, 3 drab coral bags.'
union all select 'dim white bags contain 5 shiny aqua bags, 2 shiny bronze bags, 1 plaid turquoise bag, 4 dull tomato bags.'
union all select 'vibrant plum bags contain 3 posh olive bags, 4 dark crimson bags, 3 mirrored gold bags.'
union all select 'clear cyan bags contain 5 shiny cyan bags, 2 clear fuchsia bags, 5 plaid lime bags, 1 muted green bag.'
union all select 'mirrored red bags contain 5 dotted coral bags, 3 shiny gold bags, 2 clear plum bags.'
union all select 'mirrored gray bags contain 3 clear black bags, 1 bright fuchsia bag, 1 drab teal bag, 5 faded bronze bags.'
union all select 'posh orange bags contain 2 bright cyan bags, 1 muted gray bag.'
union all select 'plaid salmon bags contain 5 dim maroon bags, 1 pale chartreuse bag, 3 posh fuchsia bags, 3 dark turquoise bags.'
union all select 'dull silver bags contain 2 mirrored maroon bags, 2 plaid lavender bags, 1 dotted red bag.'
union all select 'light plum bags contain 4 light white bags, 3 wavy lavender bags, 5 vibrant salmon bags.'
union all select 'dotted white bags contain 5 light aqua bags, 4 dim brown bags, 3 drab brown bags.'
union all select 'drab green bags contain 1 wavy black bag, 5 vibrant orange bags, 5 wavy orange bags, 1 muted purple bag.'
union all select 'pale red bags contain 3 dim tomato bags.'
union all select 'clear silver bags contain 3 clear lime bags.'
union all select 'faded gold bags contain 4 faded orange bags, 4 light bronze bags, 3 wavy gray bags.'
union all select 'drab tomato bags contain 3 clear black bags, 1 dark white bag, 5 light silver bags.'
union all select 'dull tomato bags contain 5 vibrant indigo bags, 5 dotted plum bags, 4 dull black bags.'
union all select 'light gold bags contain 2 bright gold bags, 5 faded white bags, 3 striped gold bags.'
union all select 'faded green bags contain 1 light purple bag.'
union all select 'striped gray bags contain 4 muted gray bags.'
union all select 'striped plum bags contain 2 dim coral bags.'
union all select 'dull olive bags contain 3 pale salmon bags.'
union all select 'bright tomato bags contain 2 dim bronze bags, 1 dim chartreuse bag, 5 clear purple bags.'
union all select 'wavy purple bags contain 2 faded green bags.'
union all select 'muted coral bags contain 1 faded black bag.'
union all select 'dark beige bags contain 3 mirrored gold bags, 4 posh brown bags, 1 dotted indigo bag, 3 mirrored fuchsia bags.'
union all select 'faded plum bags contain 5 dotted coral bags.'
union all select 'light maroon bags contain 3 striped violet bags.'
union all select 'wavy orange bags contain 3 plaid orange bags, 1 striped turquoise bag, 4 muted black bags, 2 posh indigo bags.'
union all select 'drab purple bags contain 4 dull lime bags, 4 posh lavender bags, 4 shiny green bags, 3 faded beige bags.'
union all select 'dim fuchsia bags contain 1 vibrant purple bag, 5 dim yellow bags.'
union all select 'plaid tan bags contain 5 posh maroon bags, 3 plaid crimson bags, 5 dim chartreuse bags.'
union all select 'light bronze bags contain 2 posh cyan bags, 5 shiny indigo bags, 1 faded silver bag, 5 shiny brown bags.'
union all select 'dotted gray bags contain 3 faded beige bags, 1 shiny turquoise bag.'
union all select 'dull white bags contain 3 muted indigo bags, 4 clear coral bags.'
union all select 'drab crimson bags contain 1 dark white bag, 1 wavy salmon bag.'
union all select 'clear maroon bags contain 1 shiny tan bag, 3 muted brown bags.'
union all select 'shiny green bags contain 2 drab black bags, 3 mirrored brown bags.'
union all select 'dark red bags contain 4 faded white bags, 5 faded plum bags.'
union all select 'dim purple bags contain 5 wavy maroon bags, 1 pale bronze bag.'
union all select 'shiny coral bags contain 1 dull olive bag, 2 wavy tomato bags, 3 dark tomato bags, 2 drab lime bags.'
union all select 'muted fuchsia bags contain 3 faded beige bags.'
union all select 'plaid silver bags contain 5 mirrored violet bags, 5 dark tomato bags.'
union all select 'vibrant gold bags contain 5 striped turquoise bags, 4 shiny gray bags, 2 muted maroon bags, 5 dark orange bags.'
union all select 'bright fuchsia bags contain 4 pale red bags, 3 posh fuchsia bags.'
union all select 'dark violet bags contain 4 drab yellow bags.'
union all select 'dim gold bags contain 5 vibrant silver bags.'
union all select 'posh tomato bags contain 1 mirrored violet bag.'
union all select 'drab yellow bags contain 1 light silver bag, 4 clear maroon bags, 5 dotted aqua bags, 1 posh maroon bag.'
union all select 'vibrant lavender bags contain 4 dim turquoise bags.'
union all select 'dotted blue bags contain 3 faded black bags.'
union all select 'plaid crimson bags contain 5 wavy gray bags, 3 striped beige bags.'
union all select 'dim green bags contain 2 bright cyan bags, 4 bright beige bags.'
union all select 'faded brown bags contain 4 posh cyan bags.'
union all select 'muted violet bags contain 4 posh aqua bags, 4 bright yellow bags, 2 drab red bags, 3 dull teal bags.'
union all select 'shiny silver bags contain 5 plaid fuchsia bags.'
union all select 'wavy olive bags contain 4 light brown bags, 4 shiny turquoise bags, 1 bright orange bag, 5 drab blue bags.'
union all select 'mirrored turquoise bags contain 1 dark lime bag, 1 faded bronze bag, 1 dark lavender bag, 3 wavy turquoise bags.'
union all select 'dark lime bags contain 3 dim bronze bags, 5 shiny turquoise bags, 1 muted gray bag.'
union all select 'striped gold bags contain 3 faded turquoise bags, 5 striped teal bags, 4 posh lavender bags.'
union all select 'light orange bags contain 5 wavy beige bags.'
union all select 'muted tomato bags contain 1 striped red bag.'
union all select 'dull blue bags contain 1 plaid aqua bag, 3 dull coral bags, 5 posh yellow bags.'
union all select 'dark plum bags contain 4 bright lavender bags, 4 dull black bags, 4 clear silver bags, 2 faded fuchsia bags.'
union all select 'light tomato bags contain 1 plaid white bag, 5 muted purple bags.'
union all select 'wavy tomato bags contain 4 vibrant teal bags, 1 plaid green bag, 1 dotted gold bag.'
union all select 'pale white bags contain 3 plaid tomato bags, 3 muted green bags, 4 light black bags.'
union all select 'vibrant fuchsia bags contain 1 shiny salmon bag, 3 faded red bags, 4 faded gray bags, 4 drab turquoise bags.'
union all select 'clear red bags contain 2 vibrant olive bags.'
union all select 'dull violet bags contain 5 dim indigo bags.'
union all select 'posh silver bags contain 1 drab tomato bag.'
union all select 'dark white bags contain 5 vibrant green bags, 3 mirrored gold bags, 2 striped beige bags.'
union all select 'mirrored maroon bags contain 1 muted teal bag, 1 muted indigo bag.'
union all select 'wavy cyan bags contain 2 striped silver bags.'
union all select 'plaid purple bags contain 2 posh olive bags, 3 vibrant salmon bags, 1 bright silver bag.'
union all select 'dull maroon bags contain 5 plaid fuchsia bags, 1 striped gray bag.'
union all select 'dark gold bags contain 5 light red bags, 4 plaid indigo bags, 1 dim aqua bag, 5 dark lavender bags.'
union all select 'plaid brown bags contain 3 shiny purple bags, 4 mirrored lime bags, 3 dark white bags.'
union all select 'dotted tan bags contain 4 striped olive bags.'
union all select 'shiny purple bags contain 5 faded indigo bags, 2 dim tan bags.'
union all select 'clear lime bags contain no other bags.'
union all select 'posh turquoise bags contain 4 drab gray bags, 5 plaid crimson bags, 4 striped silver bags.'
union all select 'dotted brown bags contain 3 dotted gold bags.'
union all select 'striped violet bags contain 2 dull white bags.'
union all select 'striped green bags contain 4 clear aqua bags, 4 posh tan bags.'
union all select 'pale tomato bags contain 5 dark maroon bags, 4 faded indigo bags, 4 dull turquoise bags, 1 bright tomato bag.'
union all select 'plaid coral bags contain 4 dark tomato bags, 1 pale purple bag, 1 faded tan bag, 5 dim tan bags.'
union all select 'shiny cyan bags contain 2 shiny magenta bags, 1 dark lavender bag, 2 vibrant blue bags.'
union all select 'light yellow bags contain 1 muted brown bag.'
union all select 'dark orange bags contain 2 dim brown bags, 5 light beige bags, 4 clear orange bags, 3 dotted blue bags.'
union all select 'drab violet bags contain 1 light turquoise bag.'
union all select 'wavy silver bags contain 3 bright magenta bags, 2 clear salmon bags.'
union all select 'clear magenta bags contain 3 shiny black bags, 3 dim brown bags, 4 dim indigo bags.'
union all select 'drab maroon bags contain 5 posh maroon bags, 3 clear orange bags, 3 dotted coral bags.'
union all select 'muted silver bags contain 3 vibrant magenta bags, 4 shiny lavender bags, 5 posh crimson bags.'
union all select 'pale gold bags contain 1 light white bag, 5 plaid chartreuse bags, 4 striped magenta bags.'
union all select 'muted turquoise bags contain 1 mirrored turquoise bag.'
union all select 'faded violet bags contain 5 shiny indigo bags.'
union all select 'clear crimson bags contain 1 faded gray bag, 5 vibrant silver bags, 5 plaid blue bags, 1 muted fuchsia bag.'
union all select 'vibrant aqua bags contain 3 dotted chartreuse bags.'
union all select 'posh brown bags contain 2 bright cyan bags, 3 shiny gold bags.'
union all select 'faded magenta bags contain 3 wavy yellow bags, 4 clear orange bags.'
union all select 'posh maroon bags contain 5 striped beige bags.'
union all select 'dotted violet bags contain 4 wavy gold bags.'
union all select 'shiny red bags contain 1 posh olive bag, 1 vibrant green bag, 4 muted purple bags.'
union all select 'posh blue bags contain 3 mirrored coral bags, 1 shiny white bag, 1 dotted salmon bag, 5 vibrant silver bags.'
union all select 'striped teal bags contain 1 striped turquoise bag, 1 faded black bag, 1 muted green bag.'
union all select 'wavy blue bags contain 4 dull lavender bags, 4 vibrant orange bags, 2 plaid white bags, 5 muted indigo bags.'
union all select 'clear gold bags contain 4 bright silver bags, 2 clear red bags, 4 dim aqua bags, 5 dim crimson bags.'
union all select 'shiny magenta bags contain 3 plaid violet bags, 4 dotted lime bags.'
union all select 'bright indigo bags contain 1 muted green bag.'
union all select 'clear white bags contain 2 vibrant chartreuse bags, 4 drab coral bags, 4 bright cyan bags.'
union all select 'clear aqua bags contain 1 bright lavender bag, 5 mirrored brown bags, 2 drab green bags, 5 muted maroon bags.'
union all select 'posh magenta bags contain 4 posh salmon bags, 3 dull crimson bags, 5 wavy violet bags, 4 bright purple bags.'
union all select 'plaid indigo bags contain 4 dull maroon bags.'
union all select 'pale magenta bags contain 5 light black bags.'
union all select 'plaid red bags contain 3 mirrored gold bags, 5 light tomato bags, 2 wavy violet bags.'
union all select 'striped olive bags contain 4 posh maroon bags, 4 wavy black bags, 4 striped beige bags.'
union all select 'drab blue bags contain 4 faded black bags, 3 dark indigo bags, 4 dim violet bags.'
union all select 'plaid bronze bags contain 3 vibrant orange bags, 3 dark aqua bags.'
union all select 'vibrant blue bags contain no other bags.'
union all select 'dark tan bags contain 5 mirrored tomato bags.'
union all select 'dotted purple bags contain 4 muted brown bags, 2 striped orange bags, 1 dark green bag.'
union all select 'mirrored white bags contain 1 clear red bag.'
union all select 'posh lime bags contain 2 posh crimson bags.'
union all select 'shiny orange bags contain 1 dark fuchsia bag.'
union all select 'faded olive bags contain 4 vibrant teal bags.'
union all select 'dull purple bags contain 3 wavy orange bags, 4 dim brown bags, 5 shiny olive bags, 2 bright beige bags.'
union all select 'dark coral bags contain 4 pale lime bags, 2 posh cyan bags.'
union all select 'pale violet bags contain 4 bright tomato bags, 5 mirrored black bags, 4 vibrant gold bags.'
union all select 'light coral bags contain 5 drab magenta bags, 2 mirrored tomato bags, 1 muted orange bag, 5 clear maroon bags.'
union all select 'pale green bags contain 2 dim aqua bags, 4 dark fuchsia bags, 2 drab salmon bags.'
union all select 'plaid gold bags contain 3 dotted lime bags, 3 faded indigo bags, 5 striped turquoise bags, 5 plaid chartreuse bags.'
union all select 'dull orange bags contain 4 mirrored coral bags, 3 dotted maroon bags, 5 striped orange bags, 3 light green bags.'
union all select 'shiny olive bags contain 4 muted purple bags, 4 plaid aqua bags, 3 dotted blue bags, 5 dotted teal bags.'
union all select 'dim coral bags contain 2 light purple bags, 1 striped beige bag, 4 striped indigo bags.'
union all select 'mirrored gold bags contain 1 vibrant blue bag, 1 dotted teal bag, 1 pale salmon bag, 3 wavy gray bags.'
union all select 'dim turquoise bags contain 1 vibrant orange bag.'
union all select 'dark teal bags contain 4 dark chartreuse bags, 5 mirrored cyan bags.'
union all select 'light silver bags contain 5 striped red bags, 3 dim bronze bags.'
union all select 'light blue bags contain 1 light beige bag, 3 posh tomato bags.'
union all select 'posh violet bags contain 2 faded maroon bags, 5 pale plum bags, 1 dotted teal bag, 3 dotted coral bags.'
union all select 'plaid teal bags contain 1 dotted chartreuse bag, 4 posh turquoise bags, 3 pale blue bags.'
union all select 'faded lime bags contain 5 mirrored gold bags, 2 plaid fuchsia bags.'
union all select 'faded aqua bags contain 4 dark tomato bags, 3 posh olive bags, 4 mirrored black bags, 1 wavy salmon bag.'
union all select 'mirrored beige bags contain 1 striped lavender bag.'
union all select 'vibrant indigo bags contain 3 plaid fuchsia bags, 1 bright lavender bag.'
union all select 'wavy tan bags contain 5 drab coral bags, 5 posh tomato bags, 4 light fuchsia bags, 3 striped tan bags.'
union all select 'shiny crimson bags contain 2 drab olive bags, 5 bright chartreuse bags, 3 faded magenta bags, 5 mirrored salmon bags.'
union all select 'dim tomato bags contain 3 pale tan bags, 5 dotted maroon bags.'
union all select 'clear indigo bags contain 2 dotted gray bags, 5 clear lime bags, 1 muted teal bag, 1 plaid green bag.'
union all select 'vibrant brown bags contain 1 vibrant beige bag.'
union all select 'dotted cyan bags contain 1 muted fuchsia bag, 4 faded olive bags, 4 mirrored lime bags.'
union all select 'mirrored crimson bags contain 2 dark indigo bags, 4 light coral bags, 5 dark silver bags.'
union all select 'dim indigo bags contain 1 plaid fuchsia bag.'
union all select 'shiny teal bags contain 4 shiny turquoise bags.'
union all select 'striped lime bags contain 1 clear purple bag, 3 pale bronze bags, 2 vibrant orange bags.'
union all select 'light tan bags contain 1 wavy gold bag, 1 light fuchsia bag.'
union all select 'clear green bags contain 1 faded olive bag, 2 vibrant coral bags.'
union all select 'wavy black bags contain 5 dotted teal bags, 3 dull fuchsia bags.'
union all select 'wavy crimson bags contain 5 shiny teal bags, 5 drab teal bags.'
union all select 'shiny tomato bags contain 4 clear chartreuse bags, 5 muted teal bags, 3 posh maroon bags.'
union all select 'dotted plum bags contain 4 dark chartreuse bags, 5 plaid orange bags.'
union all select 'dull beige bags contain 5 dim lavender bags, 3 plaid magenta bags, 4 dotted tan bags.'
union all select 'drab teal bags contain 3 posh silver bags, 1 shiny cyan bag, 1 bright teal bag.'
union all select 'faded orange bags contain 1 dark lime bag.'
union all select 'pale cyan bags contain 4 vibrant aqua bags.'
union all select 'striped red bags contain 5 dull fuchsia bags, 2 clear plum bags.'
union all select 'mirrored green bags contain 3 plaid orange bags, 3 dim aqua bags.'
union all select 'faded tomato bags contain 4 dim plum bags.'
union all select 'clear salmon bags contain 4 dim beige bags, 4 clear beige bags, 4 drab salmon bags, 2 dull turquoise bags.'
union all select 'vibrant tan bags contain 2 wavy gold bags, 1 plaid tan bag, 1 wavy bronze bag, 4 dull tomato bags.'
union all select 'vibrant salmon bags contain 1 plaid violet bag, 5 plaid green bags, 4 dark white bags, 2 muted white bags.'
union all select 'light chartreuse bags contain 3 dull cyan bags, 2 mirrored fuchsia bags.'
union all select 'mirrored bronze bags contain 4 plaid white bags, 1 drab salmon bag.'
union all select 'dull fuchsia bags contain no other bags.'
union all select 'mirrored lime bags contain 4 dotted orange bags, 5 faded tan bags, 4 faded silver bags, 5 plaid salmon bags.'
union all select 'dotted aqua bags contain 3 plaid green bags.'
union all select 'drab brown bags contain 4 dotted turquoise bags, 1 plaid orange bag, 2 striped silver bags.'
union all select 'posh black bags contain 5 faded turquoise bags, 2 dark lime bags.'
union all select 'light violet bags contain 1 bright lavender bag, 4 plaid crimson bags.'
union all select 'drab fuchsia bags contain 1 shiny beige bag, 3 dull tan bags, 3 shiny brown bags.'
union all select 'dotted bronze bags contain 4 light tomato bags, 2 light blue bags, 1 faded lavender bag, 5 bright cyan bags.'
union all select 'bright cyan bags contain 4 dull olive bags.'
union all select 'pale maroon bags contain 4 dim aqua bags.'
union all select 'bright magenta bags contain 3 striped beige bags, 3 shiny gray bags, 4 clear plum bags.'
union all select 'pale crimson bags contain 5 dim blue bags, 2 dotted fuchsia bags, 2 shiny plum bags, 1 muted fuchsia bag.'
union all select 'vibrant teal bags contain 5 dull gray bags, 5 drab coral bags, 3 clear orange bags.'
union all select 'dotted maroon bags contain 1 muted white bag, 2 dim orange bags, 4 vibrant blue bags.'
union all select 'vibrant green bags contain 3 plaid tan bags, 4 muted gray bags.'
union all select 'plaid lavender bags contain 1 pale gold bag, 2 shiny brown bags.'
union all select 'plaid plum bags contain 5 light salmon bags, 2 clear indigo bags, 2 faded bronze bags, 2 drab violet bags.'
union all select 'posh white bags contain 2 dark purple bags, 2 faded plum bags.'
union all select 'striped chartreuse bags contain 4 dark turquoise bags, 4 light beige bags, 4 vibrant purple bags, 3 bright bronze bags.'
union all select 'dim gray bags contain 4 light black bags, 1 plaid fuchsia bag.'
union all select 'clear teal bags contain 1 dotted fuchsia bag, 4 dark silver bags, 1 dark purple bag, 5 light aqua bags.'
union all select 'clear tan bags contain 3 clear red bags.'
union all select 'clear purple bags contain 3 plaid orange bags, 2 muted brown bags.'
union all select 'vibrant coral bags contain 5 dull olive bags, 2 vibrant maroon bags.'
union all select 'dim plum bags contain 2 faded salmon bags, 5 dark green bags.'
union all select 'dim cyan bags contain 3 plaid fuchsia bags, 4 dark crimson bags, 2 muted indigo bags, 2 pale lime bags.'
union all select 'striped magenta bags contain 1 clear orange bag, 5 dotted gray bags, 2 wavy gray bags.'
union all select 'dotted beige bags contain 4 shiny bronze bags, 4 drab white bags, 4 plaid indigo bags, 2 plaid gold bags.'
union all select 'dull green bags contain 2 faded salmon bags, 5 vibrant lavender bags, 4 clear gold bags.'
union all select 'light aqua bags contain 2 bright lavender bags, 4 shiny gray bags.'
union all select 'drab orange bags contain 2 pale red bags, 4 vibrant bronze bags, 4 dim purple bags.'
union all select 'posh yellow bags contain 4 wavy bronze bags, 2 light coral bags, 1 faded chartreuse bag.'
union all select 'drab coral bags contain 4 mirrored gold bags, 2 plaid tan bags, 2 wavy black bags, 2 striped beige bags.'
union all select 'muted purple bags contain no other bags.'
union all select 'bright lime bags contain 3 dotted violet bags, 2 dotted teal bags, 3 bright gray bags.'
union all select 'muted black bags contain 2 posh orange bags, 1 bright bronze bag, 1 clear lime bag.'
union all select 'dotted olive bags contain 1 vibrant violet bag, 5 clear green bags, 4 posh tomato bags.'
union all select 'striped bronze bags contain 4 pale teal bags, 1 faded yellow bag, 5 dull yellow bags.'
union all select 'light magenta bags contain 1 muted green bag, 5 dim plum bags, 2 bright tan bags, 1 plaid indigo bag.'
union all select 'pale lavender bags contain 3 dotted blue bags.'
union all select 'faded tan bags contain 1 light lime bag, 1 faded black bag, 2 light fuchsia bags.'
union all select 'mirrored coral bags contain 5 dark white bags, 4 dark orange bags, 5 faded black bags.'
union all select 'drab salmon bags contain 2 dark turquoise bags, 3 wavy plum bags, 4 dotted chartreuse bags, 5 light beige bags.'
union all select 'muted aqua bags contain 3 light beige bags.'
union all select 'light cyan bags contain 1 shiny coral bag, 5 vibrant silver bags.'
union all select 'drab turquoise bags contain 1 striped aqua bag, 1 drab lime bag.'
union all select 'wavy indigo bags contain 2 clear salmon bags, 1 dotted silver bag.'
union all select 'shiny tan bags contain 2 faded fuchsia bags, 3 faded black bags.'
union all select 'shiny gray bags contain 5 pale salmon bags, 4 shiny gold bags.'
union all select 'vibrant black bags contain 3 wavy orange bags, 3 light purple bags, 4 mirrored turquoise bags, 4 drab tomato bags.'
union all select 'dull gray bags contain no other bags.'
union all select 'dark salmon bags contain 3 striped silver bags, 4 clear indigo bags.'
union all select 'plaid black bags contain 3 dim cyan bags, 2 bright beige bags.'
union all select 'wavy gold bags contain 4 drab coral bags, 4 vibrant teal bags, 4 clear orange bags, 2 wavy black bags.'
union all select 'light lavender bags contain 4 bright plum bags, 3 light violet bags, 2 muted purple bags, 4 posh orange bags.'
union all select 'dark crimson bags contain 1 plaid tan bag, 2 muted gray bags, 5 dotted teal bags.'
union all select 'bright maroon bags contain 4 striped red bags, 4 drab maroon bags, 3 bright magenta bags.'
union all select 'dark purple bags contain 1 clear plum bag, 1 dotted gold bag.'
union all select 'dull salmon bags contain 2 faded salmon bags.'
union all select 'vibrant orange bags contain 5 posh olive bags, 4 dim cyan bags, 5 striped beige bags, 2 vibrant chartreuse bags.'
union all select 'dark maroon bags contain 1 posh brown bag, 3 dotted maroon bags.'
union all select 'vibrant crimson bags contain 3 plaid white bags, 1 clear chartreuse bag, 5 pale bronze bags, 4 dotted brown bags.'
union all select 'mirrored orange bags contain 2 pale coral bags, 1 faded indigo bag, 2 dull red bags, 1 light tan bag.'
union all select 'bright red bags contain 2 striped red bags, 5 posh tan bags.'
union all select 'faded purple bags contain 2 plaid aqua bags.'
union all select 'muted green bags contain 2 mirrored gold bags, 3 vibrant indigo bags, 1 dotted teal bag, 3 striped tan bags.'
union all select 'mirrored plum bags contain 2 wavy fuchsia bags, 1 faded turquoise bag, 5 dim purple bags.'
union all select 'dull brown bags contain 2 striped tan bags, 3 vibrant blue bags, 4 vibrant white bags, 5 dim chartreuse bags.'
union all select 'faded salmon bags contain 5 light red bags, 4 pale indigo bags, 2 posh bronze bags, 1 dull turquoise bag.'
union all select 'posh purple bags contain 3 shiny lime bags.'
union all select 'muted tan bags contain 5 dark lime bags, 3 wavy tomato bags, 2 bright teal bags.'
union all select 'dull cyan bags contain 3 vibrant green bags, 3 bright maroon bags.'
union all select 'drab white bags contain 4 wavy black bags.'
union all select 'striped black bags contain 1 posh tan bag, 5 clear orange bags.'
union all select 'mirrored yellow bags contain 4 plaid turquoise bags, 3 drab silver bags, 1 dull tomato bag.'
union all select 'dull red bags contain 4 wavy olive bags.'
union all select 'drab gray bags contain 2 striped maroon bags, 2 striped gray bags, 3 drab cyan bags.'
union all select 'faded teal bags contain 1 bright bronze bag, 5 clear tomato bags, 5 dim orange bags, 4 dim chartreuse bags.'
union all select 'muted orange bags contain 1 wavy maroon bag, 4 bright tomato bags, 1 light white bag, 2 dotted coral bags.'
union all select 'drab plum bags contain 2 muted lavender bags, 2 shiny magenta bags, 5 posh red bags, 2 bright fuchsia bags.'
union all select 'faded maroon bags contain 4 wavy tomato bags, 1 dull brown bag, 4 striped maroon bags, 3 posh aqua bags.'
union all select 'muted red bags contain 3 dull tomato bags.'
union all select 'mirrored aqua bags contain 5 posh tomato bags, 4 muted teal bags, 5 drab green bags.'
union all select 'dark brown bags contain 4 vibrant aqua bags.'
union all select 'plaid fuchsia bags contain no other bags.'
union all select 'posh tan bags contain 4 clear plum bags, 2 posh orange bags, 5 wavy gray bags.'
union all select 'striped turquoise bags contain 4 dark aqua bags.'
union all select 'drab lime bags contain 5 posh brown bags, 5 muted indigo bags, 2 dotted maroon bags, 2 clear lime bags.'
union all select 'wavy teal bags contain 2 mirrored red bags, 1 bright lavender bag, 5 dotted crimson bags, 4 faded beige bags.'
union all select 'shiny lavender bags contain 5 clear purple bags, 4 dim indigo bags, 4 shiny plum bags, 1 dull white bag.'
union all select 'dull lime bags contain 1 dim aqua bag, 1 shiny magenta bag.'
union all select 'shiny maroon bags contain 5 posh red bags, 5 dim coral bags, 4 clear crimson bags, 2 bright lime bags.'
union all select 'vibrant gray bags contain 2 plaid cyan bags, 4 plaid lime bags.'
union all select 'bright brown bags contain 1 drab lavender bag, 1 dim fuchsia bag, 4 dim olive bags, 3 wavy purple bags.'
union all select 'bright green bags contain 5 shiny red bags, 3 vibrant olive bags, 3 muted teal bags.'
union all select 'vibrant beige bags contain 4 clear olive bags, 5 striped black bags.'
union all select 'drab olive bags contain 1 vibrant white bag, 5 drab brown bags, 5 faded chartreuse bags, 5 dark lime bags.'
union all select 'wavy chartreuse bags contain 1 dull gray bag, 1 dull lavender bag, 1 mirrored green bag, 2 muted maroon bags.'
union all select 'pale indigo bags contain 5 bright beige bags, 4 dull crimson bags.'
union all select 'dull tan bags contain 5 bright lavender bags, 4 bright cyan bags, 2 dim maroon bags.'
union all select 'vibrant violet bags contain 4 dim violet bags.'
union all select 'pale salmon bags contain no other bags.'
union all select 'shiny aqua bags contain 2 plaid crimson bags, 2 mirrored red bags.'
union all select 'pale black bags contain 1 wavy chartreuse bag.'
union all select 'drab bronze bags contain 5 clear aqua bags, 3 pale brown bags.'
union all select 'light white bags contain 1 light tan bag, 3 dotted maroon bags.'
union all select 'light green bags contain 3 wavy olive bags.'
union all select 'wavy yellow bags contain 3 faded white bags, 5 wavy plum bags, 1 shiny turquoise bag.'
union all select 'wavy violet bags contain 2 pale salmon bags.'
union all select 'striped salmon bags contain 5 light turquoise bags, 4 muted tan bags.'
union all select 'muted gold bags contain 5 vibrant coral bags.'
union all select 'clear plum bags contain 4 vibrant green bags.'
union all select 'striped purple bags contain 1 posh red bag, 3 clear olive bags.'
union all select 'dim lavender bags contain 5 wavy plum bags.'
union all select 'bright gold bags contain 3 wavy brown bags, 2 mirrored magenta bags, 2 drab coral bags.'
union all select 'plaid yellow bags contain 2 plaid aqua bags, 4 pale salmon bags.'
union all select 'mirrored blue bags contain 4 posh orange bags.'
union all select 'dull turquoise bags contain 5 light teal bags, 5 striped green bags.'
union all select 'bright aqua bags contain 4 dotted lime bags.'
union all select 'light olive bags contain 3 wavy lavender bags, 5 wavy teal bags.'
union all select 'pale chartreuse bags contain 4 dark lime bags, 3 dim orange bags, 5 dotted maroon bags.'
union all select 'dim magenta bags contain 1 dark maroon bag, 3 dull olive bags, 5 dim tomato bags, 5 wavy gold bags.'
