create table adapters (jolts int)

insert into adapters select 70
insert into adapters select 102
insert into adapters select 148
insert into adapters select 9
insert into adapters select 99
insert into adapters select 63
insert into adapters select 40
insert into adapters select 52
insert into adapters select 91
insert into adapters select 39
insert into adapters select 55
insert into adapters select 28
insert into adapters select 54
insert into adapters select 22
insert into adapters select 95
insert into adapters select 61
insert into adapters select 118
insert into adapters select 35
insert into adapters select 14
insert into adapters select 21
insert into adapters select 129
insert into adapters select 82
insert into adapters select 137
insert into adapters select 45
insert into adapters select 7
insert into adapters select 87
insert into adapters select 81
insert into adapters select 25
insert into adapters select 3
insert into adapters select 108
insert into adapters select 41
insert into adapters select 11
insert into adapters select 145
insert into adapters select 18
insert into adapters select 65
insert into adapters select 80
insert into adapters select 115
insert into adapters select 29
insert into adapters select 136
insert into adapters select 42
insert into adapters select 97
insert into adapters select 104
insert into adapters select 117
insert into adapters select 141
insert into adapters select 62
insert into adapters select 121
insert into adapters select 23
insert into adapters select 96
insert into adapters select 24
insert into adapters select 128
insert into adapters select 48
insert into adapters select 1
insert into adapters select 112
insert into adapters select 8
insert into adapters select 34
insert into adapters select 144
insert into adapters select 134
insert into adapters select 116
insert into adapters select 58
insert into adapters select 147
insert into adapters select 51
insert into adapters select 84
insert into adapters select 17
insert into adapters select 126
insert into adapters select 64
insert into adapters select 68
insert into adapters select 135
insert into adapters select 10
insert into adapters select 77
insert into adapters select 105
insert into adapters select 127
insert into adapters select 73
insert into adapters select 111
insert into adapters select 90
insert into adapters select 16
insert into adapters select 103
insert into adapters select 109
insert into adapters select 98
insert into adapters select 146
insert into adapters select 123
insert into adapters select 130
insert into adapters select 69
insert into adapters select 133
insert into adapters select 110
insert into adapters select 30
insert into adapters select 122
insert into adapters select 15
insert into adapters select 74
insert into adapters select 33
insert into adapters select 38
insert into adapters select 83
insert into adapters select 92
insert into adapters select 2
insert into adapters select 53
insert into adapters select 140
insert into adapters select 4
